vich_uploader:
    db_driver: orm

    metadata:
      type: attribute

    mappings:
      post_thumbnail:
        uri_prefix: /images/posts
        upload_destination: "%kernel.project_dir%/public/images/posts"
        namer:
            service: Vich\UploaderBundle\Naming\HashNamer
            options: { algorithm: "sha256", length: 30 }
        
        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
