version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    container_name: postgres-symfony
    environment:
      POSTGRES_DB: news_db
      # You should definitely change the password in production
      POSTGRES_PASSWORD: enlil
      POSTGRES_USER: enlil
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - webdev
  ###< doctrine/doctrine-bundle ###
  pgadmin:
    container_name: pgadmin4-symfony
    image: dpage/pgadmin4
    depends_on:
      - database
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: enlil@enlil.com
      PGADMIN_DEFAULT_PASSWORD: enlil
    ports:
      - "5050:80"
    networks:
      - webdev
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-symfony
    ports: [5672, 15672]
    restart: always
    networks:
      - webdev
  portainer-ce:
    image: portainer/portainer-ce
    container_name: "portainer-symfony"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webdev

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
networks:
  webdev:
